# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loadlevel(object):
    write_to_db: QtWidgets.QPushButton
    label: QtWidgets.QLabel
    CPU: QtWidgets.QLabel
    CPU_value: QtWidgets.QLabel
    RAM: QtWidgets.QLabel
    RAM_value: QtWidgets.QLabel
    ROM: QtWidgets.QLabel
    ROM_value: QtWidgets.QLabel
    timer_label: QtWidgets.QLabel

    def __init__(self):
        self.timer_label = QtWidgets.QLabel()
        self.ROM_value = QtWidgets.QLabel()
        self.ROM = QtWidgets.QLabel()
        self.RAM_value = QtWidgets.QLabel()
        self.RAM = QtWidgets.QLabel()
        self.CPU_value = QtWidgets.QLabel()
        self.CPU = QtWidgets.QLabel()
        self.label = QtWidgets.QLabel()
        self.write_to_db = QtWidgets.QPushButton()

    def setupUi(self, loadlevel):
        loadlevel.setObjectName("loadlevel")
        loadlevel.resize(565, 394)
        loadlevel.setFixedSize(565, 450)
        self.write_to_db = QtWidgets.QPushButton(loadlevel)
        self.write_to_db.setGeometry(QtCore.QRect(212, 330, 141, 27))
        self.timer_label = QtWidgets.QLabel(loadlevel)
        self.timer_label.setGeometry(QtCore.QRect(212, 370, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timer_label.setFont(font)
        self.timer_label.setObjectName("timer_label")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.write_to_db.setFont(font)
        self.write_to_db.setObjectName("write_to_db")
        self.label = QtWidgets.QLabel(loadlevel)
        self.label.setGeometry(QtCore.QRect(30, 30, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CPU = QtWidgets.QLabel(loadlevel)
        self.CPU.setGeometry(QtCore.QRect(30, 60, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CPU.setFont(font)
        self.CPU.setObjectName("CP")
        self.CPU_value = QtWidgets.QLabel(loadlevel)
        self.CPU_value.setGeometry(QtCore.QRect(70, 60, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CPU_value.setFont(font)
        self.CPU_value.setObjectName("CP_value")
        self.RAM = QtWidgets.QLabel(loadlevel)
        self.RAM.setGeometry(QtCore.QRect(30, 90, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RAM.setFont(font)
        self.RAM.setObjectName("RAM")
        self.RAM_value = QtWidgets.QLabel(loadlevel)
        self.RAM_value.setGeometry(QtCore.QRect(70, 90, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RAM_value.setFont(font)
        self.RAM_value.setObjectName("RAM_value")
        self.ROM = QtWidgets.QLabel(loadlevel)
        self.ROM.setGeometry(QtCore.QRect(30, 120, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ROM.setFont(font)
        self.ROM.setObjectName("ROM")
        self.ROM_value = QtWidgets.QLabel(loadlevel)
        self.ROM_value.setGeometry(QtCore.QRect(70, 120, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ROM_value.setFont(font)
        self.ROM_value.setObjectName("ROM_value")

        self.retranslateUi(loadlevel)
        QtCore.QMetaObject.connectSlotsByName(loadlevel)

    def retranslateUi(self, loadlevel):
        _translate = QtCore.QCoreApplication.translate
        loadlevel.setWindowTitle(_translate("loadlevel", "Form"))
        self.write_to_db.setText(_translate("loadlevel", "Начать Запись"))
        self.label.setText(_translate("loadlevel", "Уровень загруженности:"))
        self.CPU.setText(_translate("loadlevel", "ЦП:"))
        self.CPU_value.setText(_translate("loadlevel", "0"))
        self.RAM.setText(_translate("loadlevel", "ОЗУ:"))
        self.RAM_value.setText(_translate("loadlevel", "0/0"))
        self.ROM.setText(_translate("loadlevel", "ПЗУ:"))
        self.ROM_value.setText(_translate("loadlevel", "0/0"))
        self.timer_label.setText(_translate("loadlevel", ""))
